defmodule Resellbiz.ProductTest do
  use Resellbiz.Case
  alias Resellbiz.Product

  describe "list product details" do
    test "get valid details", %{bypass: bypass} do
      Bypass.expect_once(bypass, "GET", "/api/products/details.json", fn conn ->
        assert conn.query_params == %{
                 "auth-userid" => "12345678",
                 "api-key" => "abcdefg"
               }

        response(conn, 200, product_list_json_stub())
      end)

      assert product_list_struct_stub() == Product.list_product_details()
    end
  end

  defp product_list_struct_stub do
    [
      %Resellbiz.Product.Details{
        id: "dotbz",
        service_group: "afiliascctlds",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 1,
        max_domain_length: 63,
        min_domain_secret_length: 8,
        max_domain_secret_length: 32,
        min_ns: 2,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Donuts",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["bz"]
      },
      %Resellbiz.Product.Details{
        id: "dotcreditcard",
        service_group: "donuts",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 1,
        max_domain_length: 63,
        min_domain_secret_length: 8,
        max_domain_secret_length: 32,
        min_ns: 2,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Donuts",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["creditcard"]
      },
      %Resellbiz.Product.Details{
        id: "dotfm",
        service_group: "centralnicnewgtlds",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 2,
        max_domain_length: 63,
        min_domain_secret_length: 16,
        max_domain_secret_length: 48,
        min_ns: 0,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "CentralNic",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["fm"]
      },
      %Resellbiz.Product.Details{
        id: "dotnet",
        service_group: "domcno",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: true,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 2,
        max_domain_length: 63,
        min_domain_secret_length: 8,
        max_domain_secret_length: 32,
        min_ns: 0,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Verisign",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["net"]
      },
      %Resellbiz.Product.Details{
        id: "dotproperty",
        service_group: "uniregistry",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 3,
        max_domain_length: 63,
        min_domain_secret_length: 2,
        max_domain_secret_length: 64,
        min_ns: 2,
        max_ns: 12,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Uniregistry",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["property"]
      },
      %Resellbiz.Product.Details{
        id: "dotrip",
        service_group: "demandmedia",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 1,
        max_domain_length: 63,
        min_domain_secret_length: 8,
        max_domain_secret_length: 32,
        min_ns: 2,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Donuts",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["rip"]
      },
      %Resellbiz.Product.Details{
        id: "dotsolutions",
        service_group: "donuts",
        admin_contact_group: "Contact",
        billing_contact_group: "Contact",
        owner_contact_group: "Contact",
        tech_contact_group: "Contact",
        poll_msg_support?: true,
        store_front_support?: false,
        bulk_allowed?: true,
        lock_allowed?: true,
        parking_allowed?: true,
        privacy_protection_allowed?: true,
        renewal_allowed?: true,
        restore_automated?: true,
        transfer_allowed?: true,
        transfer_secret_required?: true,
        min_domain_length: 1,
        max_domain_length: 63,
        min_domain_secret_length: 8,
        max_domain_secret_length: 32,
        min_ns: 2,
        max_ns: 13,
        min_registration_year: 1,
        max_registration_year: 10,
        min_renewal_period: 1,
        max_renewal_period: 10,
        redeemption_graceperiod: 30,
        registry: "Donuts",
        registry_add_graceperiod: 5,
        registry_autorenew_graceperiod: 45,
        tlds: ["solutions"]
      }
    ]
  end

  defp product_list_json_stub do
    %{
      "dotsolutions" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "dsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "32",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "1",
        "mindomainsecretlength" => "8",
        "minns" => "2",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Donuts",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "donuts",
        "techcontactgroup" => "Contact",
        "tldlist" => ["solutions"]
      },
      "dotnet" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "extendeddsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "true",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "32",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "2",
        "mindomainsecretlength" => "8",
        "minns" => "0",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Verisign",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "domcno",
        "techcontactgroup" => "Contact",
        "tldlist" => ["net"]
      },
      "dotproperty" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "extendeddsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "64",
        "maxns" => "12",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "3",
        "mindomainsecretlength" => "2",
        "minns" => "2",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Uniregistry",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "uniregistry",
        "techcontactgroup" => "Contact",
        "tldlist" => ["property"]
      },
      "dotcreditcard" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "dsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "32",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "1",
        "mindomainsecretlength" => "8",
        "minns" => "2",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Donuts",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "donuts",
        "techcontactgroup" => "Contact",
        "tldlist" => ["creditcard"]
      },
      "dotfm" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "extendeddsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "48",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "2",
        "mindomainsecretlength" => "16",
        "minns" => "0",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "CentralNic",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "centralnicnewgtlds",
        "techcontactgroup" => "Contact",
        "tldlist" => ["fm"]
      },
      "freeservices" => [
        "domainfwd",
        "dnsbox",
        "mailfwd",
        "premiumdomains",
        "free_email",
        "flock_service",
        "onepopmail"
      ],
      "dotbz" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "32",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "1",
        "mindomainsecretlength" => "8",
        "minns" => "2",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Donuts",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "afiliascctlds",
        "techcontactgroup" => "Contact",
        "tldlist" => ["bz"]
      },
      "dotrip" => %{
        "admincontactgroup" => "Contact",
        "billingcontactgroup" => "Contact",
        "dnssecdatasupported" => "dsdata",
        "haspollmsgsupport" => "true",
        "hasstorefrontsupport" => "false",
        "isbulkallowed" => "true",
        "islockallowed" => "true",
        "isparkingallowed" => "true",
        "isprivacyprotectionallowed" => "true",
        "isrenewallowed" => "true",
        "isrestoreautomated" => "true",
        "istransferallowed" => "true",
        "istransfersecretrequired" => "true",
        "maxdomainlength" => "63",
        "maxdomainsecretlength" => "32",
        "maxns" => "13",
        "maxregistrationyear" => "10",
        "maxrenewalperiod" => "10",
        "mindomainlength" => "1",
        "mindomainsecretlength" => "8",
        "minns" => "2",
        "minregistrationyear" => "1",
        "minrenewalperiod" => "1",
        "redeemption_graceperiod" => "30",
        "registrantcontactgroup" => "Contact",
        "registry" => "Donuts",
        "registry_add_graceperiod" => "5",
        "registry_autorenew_graceperiod" => "45",
        "servicegroup" => "demandmedia",
        "techcontactgroup" => "Contact",
        "tldlist" => ["rip"]
      }
    }
  end
end
